# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c7b866c1c2fbe816881c831eae2f01385bb28b1a3fa0f926900445c7c0d3ef08e822c92de9e2c8e9acfdf63ea26722a8b0c807a43e92be40cfd6f792463b9bf

test:
  secret_key_base: 89a82c355c65f3ad22dc4c3dfc1da22fc932f581beacfbb1f78fb958b496d5f0b1d893635e528f722ed56fae337fd35fed2b7ea40ac877e183b3ad2a38f3e608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
